name: edl-monitor-service
on:
  workflow_dispatch:
    inputs:
      env:
        type: 'choice'
        description: 'Enviroment'
        default: 'devl'
        options:
          - 'devl'
          - 'prod'
     
env:
  projectName: "edl-monitor-service"
     
jobs:
  edl-monitor-service:
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      
      - name: Node Setup
        uses: actions/setup-node@v3.0.0
        with: 
          node-version: '14.17.3'
      
      - name: AWS Credentials Dev
        if: ${{ github.event.inputs.env == 'devl' }}
        uses: github-actions-enablement/get-aws-credentials@v2
        with:
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          ROLE_ARN: "arn:aws:iam::541843007032:role/system-roles/github-actions-runners/actions-runner-edl"
          
      - name: AWS Credentials Prod
        if: ${{ github.event.inputs.env == 'prod' }}
        uses: github-actions-enablement/get-aws-credentials@v2
        with:
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          ROLE_ARN: "arn:aws:iam::305463345279:role/system-roles/github-actions-runners/actions-runner-edl"
          
      - name: Zip
        uses: EDL/ActionTemplates/.github/actions/CommonSteps/zipAndStash@master
        with:
          filename: $projectName
      
      - name: Veracode SCA
        uses: EDL/ActionTemplates/.github/actions/Veracodesca@master
        
      - name: Dev - Deploy Stack
        if: ${{ github.event.inputs.env == 'devl' }}
        uses: EDL/ActionTemplates/.github/actions/CommonSteps/vars@master
        with:
          sharedAccountNumber: 541843007032
          archFile: ci/cloudFormationTemplates/edl-monitor-service-streams-stack.j2
          variableFile: ci/config/us-east-1-devl.yml
          stackName: edl-monitor-service-streams-stack
          stackConfigFile: ci/config/stack.config
          s3Bucket: jd-us01-commoninformationservices-devl-system/templates/edg/jd-data-catalog/edl-monitor-service-streams-stack.json
          region: us-east-1
          roleName: jenkins/appslave-jenkins-edl
        
      - name: Dev - Upload Package
        if: ${{ github.event.inputs.env == 'devl' }}
        uses: EDL/ActionTemplates/.github/actions/nodeLambdaDeploy@master
        with: 
          lambdaName: DegradationHandler
          filename: edl-monitor-service.zip
          bucketName: jd-us01-commoninformationservices-devl-system
          dirName: deployment/edl
          region: us-east-1
          directDeploy: true
          
      - name: Prod - Deploy Stack
        if: ${{ github.event.inputs.env == 'prod' }}
        uses: EDL/ActionTemplates/.github/actions/CommonSteps/vars@master
        with:
          sharedAccountNumber: 305463345279
          archFile: ci/cloudFormationTemplates/edl-monitor-service-streams-stack.j2
          variableFile: ci/config/us-east-1-prod.yml
          stackName: edl-monitor-service-streams-stack
          stackConfigFile: ci/config/stack.config
          s3Bucket: jd-us01-commoninformationservices-prod-system/templates/edg/jd-data-catalog/edl-monitor-service-streams-stack.json
          region: us-east-1
          roleName: jenkins/appslave-jenkins-edl
        
      - name: Prod - Upload Package
        if: ${{ github.event.inputs.env == 'prod' }}
        uses: EDL/ActionTemplates/.github/actions/nodeLambdaDeploy@master
        with: 
          lambdaName: DegradationHandler
          filename: edl-monitor-service.zip
          bucketName: jd-us01-commoninformationservices-prod-system
          dirName: deployment/edl
          region: us-east-1
          directDeploy: true
