name: edl-current-state-deadletter-handler
on: 
  workflow_dispatch:
    inputs:
      devlOrProd:
        description: 'devl | prod'
        required: true
        default: 'devl'
  
env:
  projectName: "edl-current-state-deadletter-handler"
  isPullRequest: BRANCH_NAME ==~ /PR-([0-9]+)/
  devApproved: false
  prodApproved: false
  snowChangeCreated: false
  assignmentGroup: "AE EDL Support"
  configItem: "jd-us01-commoninformationservices-prod.${projectName}"
  baseUrl: "https://github.deere.com/EDL/${projectName}"
  submitters: env.submitters
  SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}
  PRISMA_CRED: ${{secrets.PRISMA_CRED}} 
  
jobs:
  edl-current-state-deadletter-handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
#       #Setup SAM
#       - uses: aws-actions/setup-sam@v2
#       - uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-2
      
      - name: NodeJS
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14.x'
          
      - name: SonarQube Analysis
        if: github.event.ref == 'refs/heads/main'
        # run: |
          # ${scannerHome}/bin/sonar-scanner
        run: echo "SonarQube Analysis"
          
      - name: Veracode SCA
        if: github.event.ref == 'refs/heads/main'
        run: |
          echo "'curl -sSL https://download.sourceclear.com/ci.sh | sh'"

      - name: Dev - Build and Deploy
        if: ${{github.event.inputs.devlOrProd == 'devl' && success()}}
        run: |
          sam deploy --stack-name ${edl-current-state-deadletter-handler} --s3-bucket jd-us01-commoninformationservices-${devl}-system --s3-prefix deployment/edl/${projectName}/${edl-current-state-deadletter-handler} --parameter-overrides Env=${devl} --region=us-east-1
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
