name: test2
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment Name
        options:
          - 'dev'
          - 'prod'
env:
  COOL_NAME: "hello nedim"
jobs:
  print:
    runs-on: ubuntu-latest
    steps: 
      - name: print
        if: github.event.inputs.env == 'dev'
        run: |
          echo "$COOL_NAME"
