name: edl-current-state-deadletter-handler
on: push

env:
  projectName: "edl-current-state-deadletter-handler"
  isPullRequest: BRANCH_NAME ==~ /PR-([0-9]+)/
  devApproved: false
  prodApproved: false
  snowChangeCreated: false
  assignmentGroup: "AE EDL Support"
  configItem: "jd-us01-commoninformationservices-prod.${projectName}"
  baseUrl: "https://github.deere.com/EDL/${projectName}"
  submitters: env.submitters
  SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}
  PRISMA_CRED: ${{secrets.PRISMA_CRED}} 
  
jobs:
  edl-current-state-deadletter-handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NodeJS
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14.x'
      - name: SonarQube Analysis
        if: github.event.ref == 'refs/heads/main'
        run: |
          ${scannerHome}/bin/sonar-scanner
